# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roadtrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='BE', max_length=50)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('locale', models.CharField(default='nl-NL', max_length=50)),
                ('originplace', models.CharField(default='BE', max_length=50)),
                ('destinationplace', models.CharField(default='GB', max_length=50)),
                ('outbounddate', models.DateField(default='1900-10-10')),
                ('inbounddate', models.DateField(default='1900-10-10')),
                ('adults', models.PositiveIntegerField(default='0', verbose_name=1)),
                ('budget', models.FloatField(default='0.0', verbose_name=500.0)),
                ('rooms', models.PositiveIntegerField(default='0', verbose_name=1)),
            ],
        ),
    ]
