# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadtrip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadtrip',
            name='end',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='roadtrip',
            name='start',
            field=models.DateField(auto_now=True),
        ),
    ]
