# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadtrip', '0002_remove_roadtrip_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadtrip',
            name='country',
            field=models.CharField(default='BE', max_length=50),
        ),
    ]
